const String SPLASH = 'SPLASH';

//AUTH
const String LOGIN = 'LOGIN';
const String REGISTER = 'REGISTER';

//
// DOCTOR
//
const String DOCTOR_DASHBOARD = 'DOCTOR_DASHBOARD';

// ADD PATIENT
const String DOCTOR_SCAN_QR = 'SCAN_QR';
const String DOCTOR_SCAN_RESULT = 'SCAN_RESULT';

//
// PATIENT
//
const String PATIENT_DASHBOARD = 'PATIENT_DASHBOARD';

// SCAN PRESCRIPTION
const String PATIENT_SCAN_PRESCRIPTION = 'SCAN_PRESCRIPTION';
const String PATIENT_SCAN_RESULT = 'PATIENT_SCAN_RESULT';
const String PATIENT_ADD_MEDICINE = 'PATIENT_ADD_MEDICINE';

const String PATIENT_PRESCRIPTION_SCAN = 'PATIENT_PRESCRIPTION_SCAN';

const String PATIENT_SHOW_QR = 'PATIENT_SHOW_QR';
