const String SPLASH = 'SPLASH';

//AUTH
const String LOGIN = 'LOGIN';
const String REGISTER = 'REGISTER';

//DOCTOR
const String DOCTOR_DASHBOARD = 'DOCTOR_DASHBOARD';
const String DOCTOR_ADD_PATIENT = 'ADD_PATIENT';

//PATIENT
const String PATIENT_DASHBOARD = 'PATIENT_DASHBOARD';
const String PATIENT_PRESCRIPTION_SCAN = 'PATIENT_PRESCRIPTION_SCAN';
const String PATIENT_SCAN_RESULT = 'PATIENT_SCAN_RESULT';
const String PATIENT_SHOW_QR = 'PATIENT_SHOW_QR';
